apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::521054901777:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-RBDR7Z5QEZNP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::521054901777:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-27T09:39:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1551"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 4bd72bd8-b136-4fd4-86af-cecf452d4e1a
