apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
    rolearn: arn:aws:iam::521054901777:role/UdacityFlaskDeployCBKubectlRole
    username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::521054901777:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1W0GQTD38EKCC
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-27T12:16:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1655"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 20bdabfe-5d48-4554-9539-f31c83554179
